name: CI ReactJS

on:
  pull_request:
    branches:
      - main
      - release
      - develop
      - 'features/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instala dependências
        run: npm install

      - name: Adiciona permissão de execução
        run: chmod +x ./node_modules/.bin/jest

      - name: Executa testes
        run: npm test