name: CI ReactJS

on:
  pull_request:
    branches:
      - main
      - release
      - develop
      - 'features/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código do repositório
      - name: Checkout código
        uses: actions/checkout@v3

      # Configura o Node.js
      - name: Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' 

      # Instala as dependências do projeto
      - name: Instala dependências
        run: npm install

      # PASSO NOVO E ESSENCIAL: Adiciona permissão de execução
      - name: Adiciona permissão de execução
        run: chmod +x ./node_modules/.bin/jest

      # Roda os testes
      - name: Executa testes
        run: npm test

      # Roda o build para verificar se o projeto compila sem erros (opcional para o seu projeto, mas bom ter)
      - name: Executa build
        run: npm run build