name: CI ReactJS

on:
  pull_request:
    branches:
      - main
      - release
      - develop
      - 'features/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Baixa o código do repositório
      - name: Checkout código
        uses: actions/checkout@v3

      # Configura o Node.js (versão usada pelo React)
      - name: Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # Instala as dependências do projeto
      - name: Instala dependências
        run: npm install

      # Roda os testes (React já vem com Jest configurado por padrão)
      - name: Executa testes
        run: npx jest

      # Roda o build para verificar se o projeto compila sem erros
      - name: Executa build
        run: npm run build